import * as dsp from './dsp'
import * as performance from "./performance"
import * as debug from "./debug"
import * as bytes from "./bytes" 

export {
    dsp ,
    debug,
    performance ,
    bytes 
}


declare var Date : any ; 


//  - - https://github.com/flexdinesh/browser-or-node/blob/master/src/index.js

/**
 * Returns true if the code is executing in the browser 
 */
export function is_browser() {

    return ( typeof window !== "undefined" && typeof window.document !== "undefined" ) 
} 

/**
 * Returns true if the code is executing in node  
 */
export function is_node() {
    return ( typeof process !== "undefined" &&  process.versions != null &&   process.versions.node != null ) 
} 


/**
 * Returns unix timestamp in ms
 */
export function unix_timestamp_ms() {
    return Number(new Date()) 
} 


/**
 * This function Generated by AI (Thu Jun 13 13:27:48 CDT 2024) 
 * Checks if a given string is a valid JSON string.
 *
 * @param str - The string to be checked.
 * @returns True if the string is a valid JSON string, false otherwise.
 *
 * @example
 * ```typescript
 * const jsonString = '{"name": "John", "age": 30}';
 * const notJsonString = 'Hello, world!';
 *
 * console.log(is_json_string(jsonString)); // true
 * console.log(is_json_string(notJsonString)); // false
 * ```
 */
export function is_json_string(str: string): boolean {
  try {
    JSON.parse(str);
    return true;
  } catch (e) {
    return false;
  }
}
